#include "pch.h"
OpenAvrilCLIBWriteEnableForThreadsAtSERVERINPUTACTION::WriteEnableForThreadsAt_SERVERINPUTACTION* OpenAvrilCLIBWriteEnableForThreadsAtSERVERINPUTACTION::WriteEnableForThreadsAt_SERVERINPUTACTION_Framework::_CLASS_get_ptr_WriteEnable = NULL;
OpenAvrilCLIBWriteEnableForThreadsAtSERVERINPUTACTION::WriteEnableForThreadsAt_SERVERINPUTACTION_Framework::WriteEnableForThreadsAt_SERVERINPUTACTION_Framework()
{
	boot0_CLASS_DECLAIRE_WriteEnableForThreadsAt_SERVERINPUTACTION_Framework();
	boot1_CLASS_DEFINE_WriteEnableForThreadsAt_SERVERINPUTACTION_Framework();
	boot3_CLASS_INITIALISE_WriteEnableForThreadsAt_SERVERINPUTACTION_Framework();
	boot0_REG_DECLAIRE_WriteEnableForThreadsAt_SERVERINPUTACTION_Framework();
}
OpenAvrilCLIBWriteEnableForThreadsAtSERVERINPUTACTION::WriteEnableForThreadsAt_SERVERINPUTACTION_Framework::~WriteEnableForThreadsAt_SERVERINPUTACTION_Framework()
{
	delete _CLASS_get_ptr_WriteEnable;
}
void OpenAvrilCLIBWriteEnableForThreadsAtSERVERINPUTACTION::WriteEnableForThreadsAt_SERVERINPUTACTION_Framework::boot0_CLASS_DECLAIRE_WriteEnableForThreadsAt_SERVERINPUTACTION_Framework()
{
	std::cout << "entered boot0_CLASS_DECLAIRE_WriteEnableForThreadsAt_SERVERINPUTACTION_Framework()" << std::endl;

	std::cout << "exiting boot0_CLASS_DECLAIRE_WriteEnableForThreadsAt_SERVERINPUTACTION_Framework()" << std::endl;
}
void OpenAvrilCLIBWriteEnableForThreadsAtSERVERINPUTACTION::WriteEnableForThreadsAt_SERVERINPUTACTION_Framework::boot1_CLASS_DEFINE_WriteEnableForThreadsAt_SERVERINPUTACTION_Framework()
{
	std::cout << "entered boot1_CLASS_DEFINE_WriteEnableForThreadsAt_SERVERINPUTACTION_Framework" << std::endl;
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_SERVERINPUTACTION();
	std::cout << "exiting boot1_CLASS_DEFINE_WriteEnableForThreadsAt_SERVERINPUTACTION_Framework" << std::endl;
}
void OpenAvrilCLIBWriteEnableForThreadsAtSERVERINPUTACTION::WriteEnableForThreadsAt_SERVERINPUTACTION_Framework::boot3_CLASS_INITIALISE_WriteEnableForThreadsAt_SERVERINPUTACTION_Framework()
{
	std::cout << "entered boot3_CLASS_INITIALISE_WriteEnableForThreadsAt_SERVERINPUTACTION_Framework()" << std::endl;
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_SERVERINPUTACTION();
	std::cout << "exiting boot3_CLASS_INITIALISE_WriteEnableForThreadsAt_SERVERINPUTACTION_Framework()" << std::endl;
}
void OpenAvrilCLIBWriteEnableForThreadsAtSERVERINPUTACTION::WriteEnableForThreadsAt_SERVERINPUTACTION_Framework::boot0_REG_DECLAIRE_WriteEnableForThreadsAt_SERVERINPUTACTION_Framework()
{
	std::cout << "entered boot0_REG_DECLAIRE_WriteEnableForThreadsAt_SERVERINPUTACTION_Framework()" << std::endl;

	std::cout << "exiting boot0_REG_DECLAIRE_WriteEnableForThreadsAt_SERVERINPUTACTION_Framework()" << std::endl;
}
void OpenAvrilCLIBWriteEnableForThreadsAtSERVERINPUTACTION::WriteEnableForThreadsAt_SERVERINPUTACTION_Framework::boot1_REG_DEFINE_WriteEnableForThreadsAt_SERVERINPUTACTION_Framework(OpenAvrilCLIBWriteEnableForThreadsAtSERVERINPUTACTION::WriteEnableForThreadsAt_SERVERINPUTACTION_Framework* obj)
{
	std::cout << "entered boot1_REG_DEFINE_WriteEnableForThreadsAt_SERVERINPUTACTION_Framework()" << std::endl;
	obj->dyn_CLASS_get_ptr_WriteEnable()->boot1_REG_DEFINE_WriteEnableForThreadsAt_SERVERINPUTACTION(obj);
	obj->dyn_CLASS_get_ptr_WriteEnable()->dyn_CLASS_get_ptr_Global()->boot1_REG_DEFINE_WriteEnableForThreadsAt_SERVERINPUTACTION_Global(obj);
	obj->dyn_CLASS_get_ptr_WriteEnable()->dyn_CLASS_get_ptr_WriteEnable_Control()->boot1_REG_DEFINE_WriteEnableForThreadsAt_SERVERINPUTACTION_Control(obj);
	std::cout << "exiting boot1_REG_DEFINE_WriteEnableForThreadsAt_SERVERINPUTACTION_Framework()" << std::endl;
}
void OpenAvrilCLIBWriteEnableForThreadsAtSERVERINPUTACTION::WriteEnableForThreadsAt_SERVERINPUTACTION_Framework::boot2_REG_SUBSTANTIATE_WriteEnableForThreadsAt_SERVERINPUTACTION_Framework(OpenAvrilCLIBWriteEnableForThreadsAtSERVERINPUTACTION::WriteEnableForThreadsAt_SERVERINPUTACTION_Framework* obj)
{
	std::cout << "entered boot2_REG_SUBSTANTIATE_WriteEnableForThreadsAt_SERVERINPUTACTION_Framework()" << std::endl;
	obj->dyn_CLASS_get_ptr_WriteEnable()->boot2_REG_SUBSTANTIATE_WriteEnableForThreadsAt_SERVERINPUTACTION(obj);
	obj->dyn_CLASS_get_ptr_WriteEnable()->dyn_CLASS_get_ptr_Global()->boot2_REG_SUBSTANTIATE_WriteEnableForThreadsAt_SERVERINPUTACTION_Global(obj);
	obj->dyn_CLASS_get_ptr_WriteEnable()->dyn_CLASS_get_ptr_WriteEnable_Control()->boot2_REG_SUBSTANTIATE_WriteEnableForThreadsAt_SERVERINPUTACTION_Control(obj);
	std::cout << "exiting boot2_REG_SUBSTANTIATE_WriteEnableForThreadsAt_SERVERINPUTACTION_Framework()" << std::endl;
}
void OpenAvrilCLIBWriteEnableForThreadsAtSERVERINPUTACTION::WriteEnableForThreadsAt_SERVERINPUTACTION_Framework::boot3_REG_INITIALISE_WriteEnableForThreadsAt_SERVERINPUTACTION_Framework(OpenAvrilCLIBWriteEnableForThreadsAtSERVERINPUTACTION::WriteEnableForThreadsAt_SERVERINPUTACTION_Framework* obj)
{
	std::cout << "entered boot3_REG_INITIALISE_WriteEnableForThreadsAt_SERVERINPUTACTION_Framework()" << std::endl;
	obj->dyn_CLASS_get_ptr_WriteEnable()->boot3_REG_INITIALISE_WriteEnableForThreadsAt_SERVERINPUTACTION(obj);
	obj->dyn_CLASS_get_ptr_WriteEnable()->dyn_CLASS_get_ptr_Global()->boot3_REG_INITIALISE_WriteEnableForThreadsAt_SERVERINPUTACTION_Global(obj);
	obj->dyn_CLASS_get_ptr_WriteEnable()->dyn_CLASS_get_ptr_WriteEnable_Control()->boot3_REG_INITIALISE_WriteEnableForThreadsAt_SERVERINPUTACTION_Control(obj);
	std::cout << "exiting boot3_REG_INITIALISE_WriteEnableForThreadsAt_SERVERINPUTACTION_Framework()" << std::endl;
}
void OpenAvrilCLIBWriteEnableForThreadsAtSERVERINPUTACTION::WriteEnableForThreadsAt_SERVERINPUTACTION_Framework::boot4_PGM_INSTANTIATE_WriteEnableForThreadsAt_SERVERINPUTACTION_Framework(OpenAvrilCLIBWriteEnableForThreadsAtSERVERINPUTACTION::WriteEnableForThreadsAt_SERVERINPUTACTION_Framework* obj)
{
	//if thread primed and system initialised, exit, else wait.
}
OpenAvrilCLIBWriteEnableForThreadsAtSERVERINPUTACTION::WriteEnableForThreadsAt_SERVERINPUTACTION* OpenAvrilCLIBWriteEnableForThreadsAtSERVERINPUTACTION::WriteEnableForThreadsAt_SERVERINPUTACTION_Framework::dyn_CLASS_get_ptr_WriteEnable()
{
	return stat_CLASS_get_ptr_WriteEnable();
}
void OpenAvrilCLIBWriteEnableForThreadsAtSERVERINPUTACTION::WriteEnableForThreadsAt_SERVERINPUTACTION_Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_SERVERINPUTACTION()
{
	_CLASS_get_ptr_WriteEnable = NULL;
}
void OpenAvrilCLIBWriteEnableForThreadsAtSERVERINPUTACTION::WriteEnableForThreadsAt_SERVERINPUTACTION_Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_SERVERINPUTACTION()
{
	_CLASS_get_ptr_WriteEnable = new class OpenAvrilCLIBWriteEnableForThreadsAtSERVERINPUTACTION::WriteEnableForThreadsAt_SERVERINPUTACTION();
	while (stat_CLASS_get_ptr_WriteEnable() == NULL) {}
}
OpenAvrilCLIBWriteEnableForThreadsAtSERVERINPUTACTION::WriteEnableForThreadsAt_SERVERINPUTACTION* OpenAvrilCLIBWriteEnableForThreadsAtSERVERINPUTACTION::WriteEnableForThreadsAt_SERVERINPUTACTION_Framework::stat_CLASS_get_ptr_WriteEnable()
	{
		return _CLASS_get_ptr_WriteEnable;
	}