#include "pch.h"
OpenAvrilCLIBWriteEnableForThreadsAtSERVEROUTPUTRECIEVE::WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE* OpenAvrilCLIBWriteEnableForThreadsAtSERVEROUTPUTRECIEVE::WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework::_CLASS_get_ptr_WriteEnable = NULL;
OpenAvrilCLIBWriteEnableForThreadsAtSERVEROUTPUTRECIEVE::WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework::WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework()
{
	boot0_CLASS_DECLAIRE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework();
	boot1_CLASS_DEFINE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework();
	boot3_CLASS_INITIALISE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework();
	boot0_REG_DECLAIRE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework();
}
OpenAvrilCLIBWriteEnableForThreadsAtSERVEROUTPUTRECIEVE::WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework::~WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework()
{
	delete _CLASS_get_ptr_WriteEnable;
}
void OpenAvrilCLIBWriteEnableForThreadsAtSERVEROUTPUTRECIEVE::WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework::boot0_CLASS_DECLAIRE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework()
{
	std::cout << "entered boot0_CLASS_DECLAIRE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework()" << std::endl;

	std::cout << "exiting boot0_CLASS_DECLAIRE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework()" << std::endl;
}
void OpenAvrilCLIBWriteEnableForThreadsAtSERVEROUTPUTRECIEVE::WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework::boot1_CLASS_DEFINE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework()
{
	std::cout << "entered boot1_CLASS_DEFINE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework" << std::endl;
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE();
	std::cout << "exiting boot1_CLASS_DEFINE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework" << std::endl;
}
void OpenAvrilCLIBWriteEnableForThreadsAtSERVEROUTPUTRECIEVE::WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework::boot3_CLASS_INITIALISE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework()
{
	std::cout << "entered boot3_CLASS_INITIALISE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework()" << std::endl;
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE();
	std::cout << "exiting boot3_CLASS_INITIALISE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework()" << std::endl;
}
void OpenAvrilCLIBWriteEnableForThreadsAtSERVEROUTPUTRECIEVE::WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework::boot0_REG_DECLAIRE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework()
{
	std::cout << "entered boot0_REG_DECLAIRE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework()" << std::endl;

	std::cout << "exiting boot0_REG_DECLAIRE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework()" << std::endl;
}
void OpenAvrilCLIBWriteEnableForThreadsAtSERVEROUTPUTRECIEVE::WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework::boot1_REG_DEFINE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework(OpenAvrilCLIBWriteEnableForThreadsAtSERVEROUTPUTRECIEVE::WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework* obj)
{
	std::cout << "entered boot1_REG_DEFINE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework()" << std::endl;
	obj->dyn_CLASS_get_ptr_WriteEnable()->boot1_REG_DEFINE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE(obj);
	obj->dyn_CLASS_get_ptr_WriteEnable()->dyn_CLASS_get_ptr_Global()->boot1_REG_DEFINE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Global(obj);
	obj->dyn_CLASS_get_ptr_WriteEnable()->dyn_CLASS_get_ptr_WriteEnable_Control()->boot1_REG_DEFINE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Control(obj);
	std::cout << "exiting boot1_REG_DEFINE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework()" << std::endl;
}
void OpenAvrilCLIBWriteEnableForThreadsAtSERVEROUTPUTRECIEVE::WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework::boot2_REG_SUBSTANTIATE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework(OpenAvrilCLIBWriteEnableForThreadsAtSERVEROUTPUTRECIEVE::WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework* obj)
{
	std::cout << "entered boot2_REG_SUBSTANTIATE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework()" << std::endl;
	obj->dyn_CLASS_get_ptr_WriteEnable()->boot2_REG_SUBSTANTIATE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE(obj);
	obj->dyn_CLASS_get_ptr_WriteEnable()->dyn_CLASS_get_ptr_Global()->boot2_REG_SUBSTANTIATE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Global(obj);
	obj->dyn_CLASS_get_ptr_WriteEnable()->dyn_CLASS_get_ptr_WriteEnable_Control()->boot2_REG_SUBSTANTIATE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Control(obj);
	std::cout << "exiting boot2_REG_SUBSTANTIATE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework()" << std::endl;
}
void OpenAvrilCLIBWriteEnableForThreadsAtSERVEROUTPUTRECIEVE::WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework::boot3_REG_INITIALISE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework(OpenAvrilCLIBWriteEnableForThreadsAtSERVEROUTPUTRECIEVE::WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework* obj)
{
	std::cout << "entered boot3_REG_INITIALISE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework()" << std::endl;
	obj->dyn_CLASS_get_ptr_WriteEnable()->boot3_REG_INITIALISE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE(obj);
	obj->dyn_CLASS_get_ptr_WriteEnable()->dyn_CLASS_get_ptr_Global()->boot3_REG_INITIALISE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Global(obj);
	obj->dyn_CLASS_get_ptr_WriteEnable()->dyn_CLASS_get_ptr_WriteEnable_Control()->boot3_REG_INITIALISE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Control(obj);
	std::cout << "exiting boot3_REG_INITIALISE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework()" << std::endl;
}
void OpenAvrilCLIBWriteEnableForThreadsAtSERVEROUTPUTRECIEVE::WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework::boot4_PGM_INSTANTIATE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework(OpenAvrilCLIBWriteEnableForThreadsAtSERVEROUTPUTRECIEVE::WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework* obj)
{
	//if thread primed and system initialised, exit, else wait.
}
OpenAvrilCLIBWriteEnableForThreadsAtSERVEROUTPUTRECIEVE::WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE* OpenAvrilCLIBWriteEnableForThreadsAtSERVEROUTPUTRECIEVE::WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework::dyn_CLASS_get_ptr_WriteEnable()
{
	return stat_CLASS_get_ptr_WriteEnable();
}
void OpenAvrilCLIBWriteEnableForThreadsAtSERVEROUTPUTRECIEVE::WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE()
{
	_CLASS_get_ptr_WriteEnable = NULL;
}
void OpenAvrilCLIBWriteEnableForThreadsAtSERVEROUTPUTRECIEVE::WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE()
{
	_CLASS_get_ptr_WriteEnable = new class OpenAvrilCLIBWriteEnableForThreadsAtSERVEROUTPUTRECIEVE::WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE();
	while (stat_CLASS_get_ptr_WriteEnable() == NULL) {}
}
OpenAvrilCLIBWriteEnableForThreadsAtSERVEROUTPUTRECIEVE::WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE* OpenAvrilCLIBWriteEnableForThreadsAtSERVEROUTPUTRECIEVE::WriteEnableForThreadsAt_SERVEROUTPUTRECIEVE_Framework::stat_CLASS_get_ptr_WriteEnable()
	{
		return _CLASS_get_ptr_WriteEnable;
	}