#include "pch.h"
OpenAvrilCLIBWriteEnableForThreadsAtCLIENTINPUTACTION::WriteEnableForThreadsAt_CLIENTINPUTACTION* OpenAvrilCLIBWriteEnableForThreadsAtCLIENTINPUTACTION::WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework::_CLASS_get_ptr_WriteEnable = NULL;
OpenAvrilCLIBWriteEnableForThreadsAtCLIENTINPUTACTION::WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework::WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework()
{
	boot0_CLASS_DECLAIRE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework();
	boot1_CLASS_DEFINE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework();
	boot3_CLASS_INITIALISE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework();
	boot0_REG_DECLAIRE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework();
}
OpenAvrilCLIBWriteEnableForThreadsAtCLIENTINPUTACTION::WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework::~WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework()
{
	delete _CLASS_get_ptr_WriteEnable;
}
void OpenAvrilCLIBWriteEnableForThreadsAtCLIENTINPUTACTION::WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework::boot0_CLASS_DECLAIRE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework()
{
	std::cout << "entered boot0_CLASS_DECLAIRE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework()" << std::endl;

	std::cout << "exiting boot0_CLASS_DECLAIRE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework()" << std::endl;
}
void OpenAvrilCLIBWriteEnableForThreadsAtCLIENTINPUTACTION::WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework::boot1_CLASS_DEFINE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework()
{
	std::cout << "entered boot1_CLASS_DEFINE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework" << std::endl;
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_CLIENTINPUTACTION();
	std::cout << "exiting boot1_CLASS_DEFINE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework" << std::endl;
}
void OpenAvrilCLIBWriteEnableForThreadsAtCLIENTINPUTACTION::WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework::boot3_CLASS_INITIALISE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework()
{
	std::cout << "entered boot3_CLASS_INITIALISE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework()" << std::endl;
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_CLIENTINPUTACTION();
	std::cout << "exiting boot3_CLASS_INITIALISE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework()" << std::endl;
}
void OpenAvrilCLIBWriteEnableForThreadsAtCLIENTINPUTACTION::WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework::boot0_REG_DECLAIRE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework()
{
	std::cout << "entered boot0_REG_DECLAIRE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework()" << std::endl;

	std::cout << "exiting boot0_REG_DECLAIRE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework()" << std::endl;
}
void OpenAvrilCLIBWriteEnableForThreadsAtCLIENTINPUTACTION::WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework::boot1_REG_DEFINE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework(OpenAvrilCLIBWriteEnableForThreadsAtCLIENTINPUTACTION::WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework* obj)
{
	std::cout << "entered boot1_REG_DEFINE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework()" << std::endl;
	obj->dyn_CLASS_get_ptr_WriteEnable()->boot1_REG_DEFINE_WriteEnableForThreadsAt_CLIENTINPUTACTION(obj);
	obj->dyn_CLASS_get_ptr_WriteEnable()->dyn_CLASS_get_ptr_Global()->boot1_REG_DEFINE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Global(obj);
	obj->dyn_CLASS_get_ptr_WriteEnable()->dyn_CLASS_get_ptr_WriteEnable_Control()->boot1_REG_DEFINE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Control(obj);
	std::cout << "exiting boot1_REG_DEFINE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework()" << std::endl;
}
void OpenAvrilCLIBWriteEnableForThreadsAtCLIENTINPUTACTION::WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework::boot2_REG_SUBSTANTIATE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework(OpenAvrilCLIBWriteEnableForThreadsAtCLIENTINPUTACTION::WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework* obj)
{
	std::cout << "entered boot2_REG_SUBSTANTIATE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework()" << std::endl;
	obj->dyn_CLASS_get_ptr_WriteEnable()->boot2_REG_SUBSTANTIATE_WriteEnableForThreadsAt_CLIENTINPUTACTION(obj);
	obj->dyn_CLASS_get_ptr_WriteEnable()->dyn_CLASS_get_ptr_Global()->boot2_REG_SUBSTANTIATE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Global(obj);
	obj->dyn_CLASS_get_ptr_WriteEnable()->dyn_CLASS_get_ptr_WriteEnable_Control()->boot2_REG_SUBSTANTIATE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Control(obj);
	std::cout << "exiting boot2_REG_SUBSTANTIATE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework()" << std::endl;
}
void OpenAvrilCLIBWriteEnableForThreadsAtCLIENTINPUTACTION::WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework::boot3_REG_INITIALISE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework(OpenAvrilCLIBWriteEnableForThreadsAtCLIENTINPUTACTION::WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework* obj)
{
	std::cout << "entered boot3_REG_INITIALISE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework()" << std::endl;
	obj->dyn_CLASS_get_ptr_WriteEnable()->boot3_REG_INITIALISE_WriteEnableForThreadsAt_CLIENTINPUTACTION(obj);
	obj->dyn_CLASS_get_ptr_WriteEnable()->dyn_CLASS_get_ptr_Global()->boot3_REG_INITIALISE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Global(obj);
	obj->dyn_CLASS_get_ptr_WriteEnable()->dyn_CLASS_get_ptr_WriteEnable_Control()->boot3_REG_INITIALISE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Control(obj);
	std::cout << "exiting boot3_REG_INITIALISE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework()" << std::endl;
}
void OpenAvrilCLIBWriteEnableForThreadsAtCLIENTINPUTACTION::WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework::boot4_PGM_INSTANTIATE_WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework(OpenAvrilCLIBWriteEnableForThreadsAtCLIENTINPUTACTION::WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework* obj)
{
	//if thread primed and system initialised, exit, else wait.
}
OpenAvrilCLIBWriteEnableForThreadsAtCLIENTINPUTACTION::WriteEnableForThreadsAt_CLIENTINPUTACTION* OpenAvrilCLIBWriteEnableForThreadsAtCLIENTINPUTACTION::WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework::dyn_CLASS_get_ptr_WriteEnable()
{
	return stat_CLASS_get_ptr_WriteEnable();
}
void OpenAvrilCLIBWriteEnableForThreadsAtCLIENTINPUTACTION::WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_CLIENTINPUTACTION()
{
	_CLASS_get_ptr_WriteEnable = NULL;
}
void OpenAvrilCLIBWriteEnableForThreadsAtCLIENTINPUTACTION::WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_CLIENTINPUTACTION()
{
	_CLASS_get_ptr_WriteEnable = new class OpenAvrilCLIBWriteEnableForThreadsAtCLIENTINPUTACTION::WriteEnableForThreadsAt_CLIENTINPUTACTION();
	while (stat_CLASS_get_ptr_WriteEnable() == NULL) {}
}
OpenAvrilCLIBWriteEnableForThreadsAtCLIENTINPUTACTION::WriteEnableForThreadsAt_CLIENTINPUTACTION* OpenAvrilCLIBWriteEnableForThreadsAtCLIENTINPUTACTION::WriteEnableForThreadsAt_CLIENTINPUTACTION_Framework::stat_CLASS_get_ptr_WriteEnable()
	{
		return _CLASS_get_ptr_WriteEnable;
	}